- hosts: ansible

  tasks:
  - name: create docker image
    command: docker build -t register:latest .
    args:
     chdir: /opt/docker

  - name: create tag to push image onto dockerhub
    command: docker tag register:latest heman12345/register:latest

  - name: push docker image
    command: docker push heman12345/register:latest
